import type { Metadata } from "next";
import { ReactNode } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Amazon",
  description: "Generated by create next app",
};

export default ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer
          pauseOnFocusLoss={false}
          position="top-center"
          autoClose={2000}
        />
      </body>
    </html>
  );
};
